// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package dbgen

import (
	"context"
	"time"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_log (action, entity_type, entity_id, entity_path, details, ip_address, user_agent, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAuditLogParams struct {
	Action     string    `json:"action"`
	EntityType string    `json:"entity_type"`
	EntityID   *string   `json:"entity_id"`
	EntityPath *string   `json:"entity_path"`
	Details    *string   `json:"details"`
	IpAddress  *string   `json:"ip_address"`
	UserAgent  *string   `json:"user_agent"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.EntityPath,
		arg.Details,
		arg.IpAddress,
		arg.UserAgent,
		arg.CreatedAt,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, "action", entity_type, entity_id, entity_path, details, ip_address, user_agent, created_at FROM audit_log ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListAuditLogs(ctx context.Context, limit int64) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.EntityPath,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByEntity = `-- name: ListAuditLogsByEntity :many
SELECT id, "action", entity_type, entity_id, entity_path, details, ip_address, user_agent, created_at FROM audit_log WHERE entity_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAuditLogsByEntity(ctx context.Context, entityID *string) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByEntity, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.EntityPath,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
