// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package dbgen

import (
	"context"
	"time"
)

const createAuthToken = `-- name: CreateAuthToken :exec
INSERT INTO auth_tokens (token, script_id, expires_at, created_at, ip_address, user_agent)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAuthTokenParams struct {
	Token     string    `json:"token"`
	ScriptID  string    `json:"script_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
	IpAddress *string   `json:"ip_address"`
	UserAgent *string   `json:"user_agent"`
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, createAuthToken,
		arg.Token,
		arg.ScriptID,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM auth_tokens WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredTokens, expiresAt)
	return err
}

const deleteTokensByScript = `-- name: DeleteTokensByScript :exec
DELETE FROM auth_tokens WHERE script_id = ?
`

func (q *Queries) DeleteTokensByScript(ctx context.Context, scriptID string) error {
	_, err := q.db.ExecContext(ctx, deleteTokensByScript, scriptID)
	return err
}

const getAuthToken = `-- name: GetAuthToken :one
SELECT token, script_id, expires_at, created_at, ip_address, user_agent FROM auth_tokens WHERE token = ?
`

func (q *Queries) GetAuthToken(ctx context.Context, token string) (AuthToken, error) {
	row := q.db.QueryRowContext(ctx, getAuthToken, token)
	var i AuthToken
	err := row.Scan(
		&i.Token,
		&i.ScriptID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.IpAddress,
		&i.UserAgent,
	)
	return i, err
}
