// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folders.sql

package dbgen

import (
	"context"
	"time"
)

const createFolder = `-- name: CreateFolder :exec
INSERT INTO folders (id, path, name, created_at) VALUES (?, ?, ?, ?)
`

type CreateFolderParams struct {
	ID        string    `json:"id"`
	Path      string    `json:"path"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) error {
	_, err := q.db.ExecContext(ctx, createFolder,
		arg.ID,
		arg.Path,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders WHERE id = ?
`

func (q *Queries) DeleteFolder(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFolder, id)
	return err
}

const deleteFolderByPath = `-- name: DeleteFolderByPath :exec
DELETE FROM folders WHERE path = ? OR path LIKE ? || '/%'
`

type DeleteFolderByPathParams struct {
	Path    string  `json:"path"`
	Column2 *string `json:"column_2"`
}

func (q *Queries) DeleteFolderByPath(ctx context.Context, arg DeleteFolderByPathParams) error {
	_, err := q.db.ExecContext(ctx, deleteFolderByPath, arg.Path, arg.Column2)
	return err
}

const getFolder = `-- name: GetFolder :one
SELECT id, path, name, created_at FROM folders WHERE id = ?
`

func (q *Queries) GetFolder(ctx context.Context, id string) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolder, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getFolderByPath = `-- name: GetFolderByPath :one
SELECT id, path, name, created_at FROM folders WHERE path = ?
`

func (q *Queries) GetFolderByPath(ctx context.Context, path string) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolderByPath, path)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listFolders = `-- name: ListFolders :many
SELECT id, path, name, created_at FROM folders ORDER BY path
`

func (q *Queries) ListFolders(ctx context.Context) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubfolders = `-- name: ListSubfolders :many
SELECT id, path, name, created_at FROM folders WHERE path LIKE ? || '/%' AND path NOT LIKE ? || '/%/%' ORDER BY name
`

type ListSubfoldersParams struct {
	Column1 *string `json:"column_1"`
	Column2 *string `json:"column_2"`
}

func (q *Queries) ListSubfolders(ctx context.Context, arg ListSubfoldersParams) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listSubfolders, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
