// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type AuditLog struct {
	ID         int64     `json:"id"`
	Action     string    `json:"action"`
	EntityType string    `json:"entity_type"`
	EntityID   *string   `json:"entity_id"`
	EntityPath *string   `json:"entity_path"`
	Details    *string   `json:"details"`
	IpAddress  *string   `json:"ip_address"`
	UserAgent  *string   `json:"user_agent"`
	CreatedAt  time.Time `json:"created_at"`
}

type AuthToken struct {
	Token     string    `json:"token"`
	ScriptID  string    `json:"script_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
	IpAddress *string   `json:"ip_address"`
	UserAgent *string   `json:"user_agent"`
}

type Folder struct {
	ID        string    `json:"id"`
	Path      string    `json:"path"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type Script struct {
	ID           string    `json:"id"`
	Path         string    `json:"path"`
	Name         string    `json:"name"`
	Content      string    `json:"content"`
	Description  *string   `json:"description"`
	Tags         *string   `json:"tags"`
	Locked       int64     `json:"locked"`
	PasswordHash *string   `json:"password_hash"`
	DangerLevel  *int64    `json:"danger_level"`
	Requires     *string   `json:"requires"`
	Examples     *string   `json:"examples"`
	Favorite     int64     `json:"favorite"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type ScriptVersion struct {
	ID        int64     `json:"id"`
	ScriptID  string    `json:"script_id"`
	Content   string    `json:"content"`
	Version   int64     `json:"version"`
	CreatedAt time.Time `json:"created_at"`
}
