// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scripts.sql

package dbgen

import (
	"context"
	"time"
)

const createScript = `-- name: CreateScript :exec
INSERT INTO scripts (id, path, name, content, description, tags, locked, password_hash, danger_level, requires, examples, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateScriptParams struct {
	ID           string    `json:"id"`
	Path         string    `json:"path"`
	Name         string    `json:"name"`
	Content      string    `json:"content"`
	Description  *string   `json:"description"`
	Tags         *string   `json:"tags"`
	Locked       int64     `json:"locked"`
	PasswordHash *string   `json:"password_hash"`
	DangerLevel  *int64    `json:"danger_level"`
	Requires     *string   `json:"requires"`
	Examples     *string   `json:"examples"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) CreateScript(ctx context.Context, arg CreateScriptParams) error {
	_, err := q.db.ExecContext(ctx, createScript,
		arg.ID,
		arg.Path,
		arg.Name,
		arg.Content,
		arg.Description,
		arg.Tags,
		arg.Locked,
		arg.PasswordHash,
		arg.DangerLevel,
		arg.Requires,
		arg.Examples,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteScript = `-- name: DeleteScript :exec
DELETE FROM scripts WHERE id = ?
`

func (q *Queries) DeleteScript(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteScript, id)
	return err
}

const getScript = `-- name: GetScript :one
SELECT id, path, name, content, description, tags, locked, password_hash, danger_level, requires, examples, favorite, created_at, updated_at FROM scripts WHERE id = ?
`

func (q *Queries) GetScript(ctx context.Context, id string) (Script, error) {
	row := q.db.QueryRowContext(ctx, getScript, id)
	var i Script
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Name,
		&i.Content,
		&i.Description,
		&i.Tags,
		&i.Locked,
		&i.PasswordHash,
		&i.DangerLevel,
		&i.Requires,
		&i.Examples,
		&i.Favorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScriptByPath = `-- name: GetScriptByPath :one
SELECT id, path, name, content, description, tags, locked, password_hash, danger_level, requires, examples, favorite, created_at, updated_at FROM scripts WHERE path = ?
`

func (q *Queries) GetScriptByPath(ctx context.Context, path string) (Script, error) {
	row := q.db.QueryRowContext(ctx, getScriptByPath, path)
	var i Script
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Name,
		&i.Content,
		&i.Description,
		&i.Tags,
		&i.Locked,
		&i.PasswordHash,
		&i.DangerLevel,
		&i.Requires,
		&i.Examples,
		&i.Favorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFavorites = `-- name: ListFavorites :many
SELECT id, path, name, content, description, tags, locked, password_hash, danger_level, requires, examples, favorite, created_at, updated_at FROM scripts WHERE favorite = 1 ORDER BY path
`

func (q *Queries) ListFavorites(ctx context.Context) ([]Script, error) {
	rows, err := q.db.QueryContext(ctx, listFavorites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Script{}
	for rows.Next() {
		var i Script
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Name,
			&i.Content,
			&i.Description,
			&i.Tags,
			&i.Locked,
			&i.PasswordHash,
			&i.DangerLevel,
			&i.Requires,
			&i.Examples,
			&i.Favorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentlyUpdated = `-- name: ListRecentlyUpdated :many
SELECT id, path, name, content, description, tags, locked, password_hash, danger_level, requires, examples, favorite, created_at, updated_at FROM scripts ORDER BY updated_at DESC LIMIT ?
`

func (q *Queries) ListRecentlyUpdated(ctx context.Context, limit int64) ([]Script, error) {
	rows, err := q.db.QueryContext(ctx, listRecentlyUpdated, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Script{}
	for rows.Next() {
		var i Script
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Name,
			&i.Content,
			&i.Description,
			&i.Tags,
			&i.Locked,
			&i.PasswordHash,
			&i.DangerLevel,
			&i.Requires,
			&i.Examples,
			&i.Favorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScripts = `-- name: ListScripts :many
SELECT id, path, name, content, description, tags, locked, password_hash, danger_level, requires, examples, favorite, created_at, updated_at FROM scripts ORDER BY path
`

func (q *Queries) ListScripts(ctx context.Context) ([]Script, error) {
	rows, err := q.db.QueryContext(ctx, listScripts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Script{}
	for rows.Next() {
		var i Script
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Name,
			&i.Content,
			&i.Description,
			&i.Tags,
			&i.Locked,
			&i.PasswordHash,
			&i.DangerLevel,
			&i.Requires,
			&i.Examples,
			&i.Favorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScriptsByFolder = `-- name: ListScriptsByFolder :many
SELECT id, path, name, content, description, tags, locked, password_hash, danger_level, requires, examples, favorite, created_at, updated_at FROM scripts WHERE path LIKE ? || '/%' AND path NOT LIKE ? || '/%/%' ORDER BY name
`

type ListScriptsByFolderParams struct {
	Column1 *string `json:"column_1"`
	Column2 *string `json:"column_2"`
}

func (q *Queries) ListScriptsByFolder(ctx context.Context, arg ListScriptsByFolderParams) ([]Script, error) {
	rows, err := q.db.QueryContext(ctx, listScriptsByFolder, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Script{}
	for rows.Next() {
		var i Script
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Name,
			&i.Content,
			&i.Description,
			&i.Tags,
			&i.Locked,
			&i.PasswordHash,
			&i.DangerLevel,
			&i.Requires,
			&i.Examples,
			&i.Favorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchScripts = `-- name: SearchScripts :many
SELECT id, path, name, content, description, tags, locked, password_hash, danger_level, requires, examples, favorite, created_at, updated_at FROM scripts 
WHERE name LIKE '%' || ? || '%' 
   OR path LIKE '%' || ? || '%'
   OR description LIKE '%' || ? || '%'
   OR tags LIKE '%' || ? || '%'
ORDER BY path
`

type SearchScriptsParams struct {
	Column1 *string `json:"column_1"`
	Column2 *string `json:"column_2"`
	Column3 *string `json:"column_3"`
	Column4 *string `json:"column_4"`
}

func (q *Queries) SearchScripts(ctx context.Context, arg SearchScriptsParams) ([]Script, error) {
	rows, err := q.db.QueryContext(ctx, searchScripts,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Script{}
	for rows.Next() {
		var i Script
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Name,
			&i.Content,
			&i.Description,
			&i.Tags,
			&i.Locked,
			&i.PasswordHash,
			&i.DangerLevel,
			&i.Requires,
			&i.Examples,
			&i.Favorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFavorite = `-- name: SetFavorite :exec
UPDATE scripts SET favorite = ? WHERE id = ?
`

type SetFavoriteParams struct {
	Favorite int64  `json:"favorite"`
	ID       string `json:"id"`
}

func (q *Queries) SetFavorite(ctx context.Context, arg SetFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, setFavorite, arg.Favorite, arg.ID)
	return err
}

const updateScript = `-- name: UpdateScript :exec
UPDATE scripts SET 
    path = ?,
    name = ?,
    content = ?,
    description = ?,
    tags = ?,
    locked = ?,
    password_hash = ?,
    danger_level = ?,
    requires = ?,
    examples = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateScriptParams struct {
	Path         string    `json:"path"`
	Name         string    `json:"name"`
	Content      string    `json:"content"`
	Description  *string   `json:"description"`
	Tags         *string   `json:"tags"`
	Locked       int64     `json:"locked"`
	PasswordHash *string   `json:"password_hash"`
	DangerLevel  *int64    `json:"danger_level"`
	Requires     *string   `json:"requires"`
	Examples     *string   `json:"examples"`
	UpdatedAt    time.Time `json:"updated_at"`
	ID           string    `json:"id"`
}

func (q *Queries) UpdateScript(ctx context.Context, arg UpdateScriptParams) error {
	_, err := q.db.ExecContext(ctx, updateScript,
		arg.Path,
		arg.Name,
		arg.Content,
		arg.Description,
		arg.Tags,
		arg.Locked,
		arg.PasswordHash,
		arg.DangerLevel,
		arg.Requires,
		arg.Examples,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateScriptContent = `-- name: UpdateScriptContent :exec
UPDATE scripts SET content = ?, updated_at = ? WHERE id = ?
`

type UpdateScriptContentParams struct {
	Content   string    `json:"content"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateScriptContent(ctx context.Context, arg UpdateScriptContentParams) error {
	_, err := q.db.ExecContext(ctx, updateScriptContent, arg.Content, arg.UpdatedAt, arg.ID)
	return err
}

const updateScriptLock = `-- name: UpdateScriptLock :exec
UPDATE scripts SET locked = ?, password_hash = ?, updated_at = ? WHERE id = ?
`

type UpdateScriptLockParams struct {
	Locked       int64     `json:"locked"`
	PasswordHash *string   `json:"password_hash"`
	UpdatedAt    time.Time `json:"updated_at"`
	ID           string    `json:"id"`
}

func (q *Queries) UpdateScriptLock(ctx context.Context, arg UpdateScriptLockParams) error {
	_, err := q.db.ExecContext(ctx, updateScriptLock,
		arg.Locked,
		arg.PasswordHash,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
