// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: versions.sql

package dbgen

import (
	"context"
	"time"
)

const createVersion = `-- name: CreateVersion :exec
INSERT INTO script_versions (script_id, content, version, created_at)
VALUES (?, ?, ?, ?)
`

type CreateVersionParams struct {
	ScriptID  string    `json:"script_id"`
	Content   string    `json:"content"`
	Version   int64     `json:"version"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateVersion(ctx context.Context, arg CreateVersionParams) error {
	_, err := q.db.ExecContext(ctx, createVersion,
		arg.ScriptID,
		arg.Content,
		arg.Version,
		arg.CreatedAt,
	)
	return err
}

const getLatestVersion = `-- name: GetLatestVersion :one
SELECT MAX(version) as version FROM script_versions WHERE script_id = ?
`

func (q *Queries) GetLatestVersion(ctx context.Context, scriptID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLatestVersion, scriptID)
	var version interface{}
	err := row.Scan(&version)
	return version, err
}

const getVersion = `-- name: GetVersion :one
SELECT id, script_id, content, version, created_at FROM script_versions WHERE script_id = ? AND version = ?
`

type GetVersionParams struct {
	ScriptID string `json:"script_id"`
	Version  int64  `json:"version"`
}

func (q *Queries) GetVersion(ctx context.Context, arg GetVersionParams) (ScriptVersion, error) {
	row := q.db.QueryRowContext(ctx, getVersion, arg.ScriptID, arg.Version)
	var i ScriptVersion
	err := row.Scan(
		&i.ID,
		&i.ScriptID,
		&i.Content,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const listVersions = `-- name: ListVersions :many
SELECT id, script_id, content, version, created_at FROM script_versions WHERE script_id = ? ORDER BY version DESC
`

func (q *Queries) ListVersions(ctx context.Context, scriptID string) ([]ScriptVersion, error) {
	rows, err := q.db.QueryContext(ctx, listVersions, scriptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScriptVersion{}
	for rows.Next() {
		var i ScriptVersion
		if err := rows.Scan(
			&i.ID,
			&i.ScriptID,
			&i.Content,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
